version: '3.1'
services:

  postgres-service:
    container_name: todolistdb
    ports:
      - "5432:5432"
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres